function spawnBox(modelName, x, y, z, l, w, h)
% TODO: controrl width height length and start position
system(['source ~/catkin_ws/devel/setup.bash; rosrun xacro xacro ~/catkin_ws/src/comprobo18/com_workshop/urdf/redBox.xacro',...
        ' length:=',num2str(l),...
        ' width:=',num2str(w),...
        ' height:=',num2str(h),...
        '| rosrun gazebo_ros spawn_model -stdin',...
        ' -model ',modelName,...
        ' -urdf -x ', num2str(x),...
        ' -y ', num2str(y),...
        ' -z ', num2str(z)]);
end